#!/usr/bin/env bash
# apply.sh — Applies dashboard/alert files generated by obs-panel/obs-alert (or otel-bootstrap)
# to a real Grafana instance. Dry-run by default; requires --apply to write anything.
#
# Usage:
#   apply.sh [--apply] <file.json|file.yaml> [more files...]
#
# Env vars required (read from this repo's .env, or the shell environment as a fallback):
#   GRAFANA_URL          — e.g. https://grafana.internal
#   GRAFANA_ADMIN_TOKEN   — a token distinct from GRAFANA_SERVICE_ACCOUNT_TOKEN (used by the
#                          read-only agents). This one needs Editor rights to write dashboards
#                          and alert rules — keep it out of the agents' reach.
#
# Dashboards (*.json): POST /api/dashboards/db
#   https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#create--update-dashboard
#
# Alerts (*.yaml/*.yml, provisioning group format): PUT /api/v1/provisioning/folder/:folderUid/rule-groups/:group
#   https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/
#   The X-Disable-Provenance header is intentionally NOT sent, so rules created this way stay
#   read-only in the Grafana UI — git remains the source of truth.
#
# Alert application is best-effort: it maps this repo's alert-rules.yaml.tmpl shape onto the
# provisioning rule-group API. Verify with --apply against a non-production Grafana before
# trusting it against production.
#
# Exit codes: 0 = OK, 1 = validation/apply error, 2 = usage/missing dependency

set -euo pipefail

APPLY=false
FILES=()

for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=true ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) FILES+=("$arg") ;;
  esac
done

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "Usage: apply.sh [--apply] <file.json|file.yaml> [more files...]" >&2
  exit 2
fi

command -v jq >/dev/null 2>&1 || { echo "error: 'jq' is required (brew install jq)"; exit 2; }

NEEDS_YQ=false
for f in "${FILES[@]}"; do
  case "$f" in *.yaml|*.yml) NEEDS_YQ=true ;; esac
done
if [ "$NEEDS_YQ" = true ] && ! command -v yq >/dev/null 2>&1; then
  echo "error: 'yq' (mikefarah/yq) is required to apply alert-rule YAML (brew install yq)"
  exit 2
fi

# Load this repo's .env (if present) — fills gaps without overriding vars already
# exported in the shell. Resolved relative to this script's own location so it works
# whether it's invoked via the real repo path or a symlinked ~/.claude/skills/ copy.
# `cd -P` (physical) is required, not plain `cd`+`pwd`: bash's `cd` in its default
# logical mode collapses ".." by string manipulation, so it never actually dereferences
# the `skills/obs-apply` symlink — it lands inside ~/.claude instead of the real repo.
REPO_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && cd -P ../../.. && pwd -P)"
if [ -f "$REPO_ROOT/.env" ]; then
  # Filter to a real temp file rather than `source <(...)` — bash 3.2 (macOS's
  # stock /bin/bash) silently sources nothing when given a process-substitution fd.
  FILTERED_ENV="$(mktemp)"
  trap 'rm -f "$FILTERED_ENV"' EXIT
  # Skip blank assignments (KEY=) so an unfilled .env placeholder never clobbers a
  # same-named variable already exported in the parent shell.
  # `|| true`: grep exits 1 when every line is filtered out (e.g. an all-blank .env),
  # which is a valid outcome here, not an error — set -e must not treat it as one.
  grep -v -E '^\s*[A-Za-z_][A-Za-z0-9_]*=\s*$' "$REPO_ROOT/.env" > "$FILTERED_ENV" || true
  set -a
  # shellcheck disable=SC1091
  source "$FILTERED_ENV"
  set +a
fi

: "${GRAFANA_URL:?GRAFANA_URL must be set (in $REPO_ROOT/.env or the shell environment)}"
: "${GRAFANA_ADMIN_TOKEN:?GRAFANA_ADMIN_TOKEN must be set (distinct from GRAFANA_SERVICE_ACCOUNT_TOKEN)}"

GRAFANA_URL="${GRAFANA_URL%/}"
AUTH_HEADER="Authorization: Bearer ${GRAFANA_ADMIN_TOKEN}"
MODE="DRY-RUN"
[ "$APPLY" = true ] && MODE="APPLY"
echo "mode: $MODE"
echo "grafana: $GRAFANA_URL"
echo ""

ERRORS=0

check_no_placeholders() {
  # Match only known skill/template placeholders (SERVICE_*, EXPORTED_JOB) — not
  # Grafana's own `{{ le }}` / `{{ http_route }}` legend-format templating, which
  # is legitimate and present in nearly every real dashboard panel.
  if grep -qE '\{\{(SERVICE_[A-Z]+|EXPORTED_JOB)\}\}' "$1"; then
    echo "  FAIL  $1: unreplaced {{...}} placeholder remains"
    ERRORS=$((ERRORS + 1))
    return 1
  fi
  return 0
}

# resolve_folder_uid <title> -> prints uid, creates the folder if missing (GET is always safe;
# creation only happens under --apply; in dry-run a missing folder is reported, not created).
resolve_folder_uid() {
  local title="$1"
  local uid
  uid=$(curl -sf -H "$AUTH_HEADER" "$GRAFANA_URL/api/folders" \
    | jq -r --arg t "$title" '.[] | select(.title == $t) | .uid' | head -1)

  if [ -n "$uid" ]; then
    echo "$uid"
    return 0
  fi

  if [ "$APPLY" = true ]; then
    curl -sf -X POST -H "$AUTH_HEADER" -H "Content-Type: application/json" \
      -d "$(jq -n --arg t "$title" '{title: $t}')" \
      "$GRAFANA_URL/api/folders" | jq -r '.uid'
  else
    echo "(would create)"
  fi
}

url_encode() {
  jq -rn --arg s "$1" '$s | @uri'
}

# duration_to_seconds "1m" -> 60 ; "30s" -> 30 ; "2h" -> 7200
duration_to_seconds() {
  local d="$1" unit="${1: -1}" num="${1%?}"
  case "$unit" in
    s) echo "$num" ;;
    m) echo $((num * 60)) ;;
    h) echo $((num * 3600)) ;;
    *) echo "$d" ;; # already a plain number
  esac
}

# resolve_dashboard_uid <title> -> prints the uid of a live dashboard with this exact
# title, if one exists. Read-only (GET /api/search) — safe to call in dry-run too.
# Grafana's dashboard API matches by uid, not title, so applying a file with no uid
# against an already-imported dashboard creates a duplicate instead of updating it.
resolve_dashboard_uid() {
  local title="$1"
  curl -sf -H "$AUTH_HEADER" -G --data-urlencode "query=$title" "$GRAFANA_URL/api/search" \
    | jq -r --arg t "$title" '[.[] | select(.title == $t and .type == "dash-db")][0].uid // empty'
}

apply_dashboard() {
  local f="$1"
  echo "-- dashboard: $f"

  if ! jq . "$f" > /dev/null 2>&1; then
    echo "  FAIL  invalid JSON"
    ERRORS=$((ERRORS + 1))
    return
  fi
  check_no_placeholders "$f" || return

  local title uid panel_count payload
  title=$(jq -r '.title // "(untitled)"' "$f")
  uid=$(jq -r '.uid // empty' "$f")
  panel_count=$(jq '.panels | length' "$f")

  if [ -z "$uid" ]; then
    uid=$(resolve_dashboard_uid "$title")
    if [ -n "$uid" ]; then
      echo "  title: $title  uid: (none in file — found live uid=$uid by title match, will update it)  panels: $panel_count"
    else
      echo "  title: $title  uid: (none — no live dashboard with this title found, will create new)  panels: $panel_count"
    fi
  else
    echo "  title: $title  uid: $uid  panels: $panel_count"
  fi

  payload=$(jq -n --slurpfile dash "$f" --arg uid "$uid" \
    '{dashboard: ($dash[0] | .id = null | if $uid != "" then .uid = $uid else . end), overwrite: true, message: "applied via obs-apply"}')

  if [ "$APPLY" = false ]; then
    echo "  would POST $GRAFANA_URL/api/dashboards/db"
    return
  fi

  if curl -sf -X POST -H "$AUTH_HEADER" -H "Content-Type: application/json" \
      -d "$payload" "$GRAFANA_URL/api/dashboards/db" > /dev/null; then
    echo "  OK    applied"
  else
    echo "  FAIL  POST /api/dashboards/db failed"
    ERRORS=$((ERRORS + 1))
  fi
}

apply_alert_file() {
  local f="$1"
  echo "-- alert rules: $f"
  check_no_placeholders "$f" || return

  local json group_count
  json=$(yq -o=json '.' "$f")
  group_count=$(echo "$json" | jq '.groups | length')
  echo "  groups: $group_count"

  local i
  for i in $(seq 0 $((group_count - 1))); do
    local group folder_title group_name interval_s rule_count folder_uid rules_payload
    group=$(echo "$json" | jq ".groups[$i]")
    folder_title=$(echo "$group" | jq -r '.folder')
    group_name=$(echo "$group" | jq -r '.name')
    interval_s=$(duration_to_seconds "$(echo "$group" | jq -r '.interval')")
    rule_count=$(echo "$group" | jq '.rules | length')
    echo "  group '$group_name' (folder: $folder_title, interval: ${interval_s}s, rules: $rule_count)"

    folder_uid=$(resolve_folder_uid "$folder_title")
    echo "    folder uid: $folder_uid"

    rules_payload=$(echo "$group" | jq --argjson interval "$interval_s" \
      '{name: .name, interval: $interval, rules: .rules}')

    local encoded_folder_uid encoded_group_name
    encoded_folder_uid=$(url_encode "$folder_uid")
    encoded_group_name=$(url_encode "$group_name")

    if [ "$APPLY" = false ]; then
      echo "    would PUT $GRAFANA_URL/api/v1/provisioning/folder/$encoded_folder_uid/rule-groups/$encoded_group_name"
      continue
    fi

    if curl -sf -X PUT -H "$AUTH_HEADER" -H "Content-Type: application/json" \
        -d "$rules_payload" \
        "$GRAFANA_URL/api/v1/provisioning/folder/$encoded_folder_uid/rule-groups/$encoded_group_name" > /dev/null; then
      echo "    OK    applied"
    else
      echo "    FAIL  PUT rule-group failed"
      ERRORS=$((ERRORS + 1))
    fi
  done
}

for f in "${FILES[@]}"; do
  case "$f" in
    *.json) apply_dashboard "$f" ;;
    *.yaml|*.yml) apply_alert_file "$f" ;;
    *) echo "  SKIP  $f (unknown extension, expected .json/.yaml/.yml)" ;;
  esac
  echo ""
done

if [ "$ERRORS" -gt 0 ]; then
  echo "FAILED: $ERRORS error(s)."
  exit 1
fi

if [ "$APPLY" = false ]; then
  echo "dry-run complete — no changes were made. Re-run with --apply to write."
else
  echo "apply complete."
fi
